#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LJH.RegionMonitor.AndroidAPP.Resource", IsApplication=true)]

namespace LJH.RegionMonitor.AndroidAPP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int myicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int view = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int lblCardID = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int lblCount = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int lblDept = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int lblDoor = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int lblName = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int lblPhone = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int lblTime = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int lblUser = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int lvRegion = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int picPhoto = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int txtCardID = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int txtDept = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int txtDoor = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int txtName = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int txtPhone = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int txtTime = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int userGridview = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int FrmUserDetail = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int InregionDeptView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int InregionPersonView = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int myicon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int app_title = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
