#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LJH.RegionMonitor.AndroidAPP.Resource", IsApplication=true)]

namespace LJH.RegionMonitor.AndroidAPP
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.1.0.5")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int alarm = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int myicon = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int view = 2130771970;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int lblCardID = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int lblCount = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int lblDept = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int lblDoor = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int lblName = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int lblPhone = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int lblTime = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int lblUser = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int lvRegion = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int picAlarm = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int picPhoto = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int txtCardID = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int txtDept = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int txtDoor = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int txtName = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int txtPhone = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int txtTime = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int userGridview = 2130837521;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int FrmUserDetail = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int InregionDeptView = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int InregionPersonView = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int myicon = 2130968576;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F050000
			public const int Alerting = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int app_title = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
